{
    "./resources/scenes/area1files/imgs/Ghost.png1": {
        "alpha": 255,
        "children": null,
        "facingRight": true,
        "filepath": "./resources/scenes/area1files/imgs/Ghost.png",
        "height": 100,
        "id": "./resources/scenes/area1files/imgs/Ghost.png1",
        "pivot.x": 0,
        "pivot.y": 0,
        "position.x": 400,
        "position.y": 400,
        "rotation": 0.0,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "type": "DisplayObjectContainer",
        "visible": true,
        "width": 100
    },
    "./resources/scenes/area1files/imgs/Prop_5.png0": {
        "alpha": 255,
        "children": null,
        "facingRight": true,
        "filepath": "./resources/scenes/area1files/imgs/Prop_5.png",
        "height": 100,
        "id": "./resources/scenes/area1files/imgs/Prop_5.png0",
        "pivot.x": 0,
        "pivot.y": 0,
        "position.x": 100,
        "position.y": 400,
        "rotation": 0.0,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "type": "DisplayObjectContainer",
        "visible": true,
        "width": 100
    },
    "./resources/scenes/area1files/imgs/frog2.png2": {
        "alpha": 255,
        "children": {
            "selected": {
                "alpha": 70,
                "children": null,
                "facingRight": true,
                "filepath": "",
                "height": 100,
                "id": "selected",
                "pivot.x": 0,
                "pivot.y": 0,
                "position.x": 0,
                "position.y": 0,
                "rotation": 0.0,
                "scaleX": 1.0,
                "scaleY": 1.0,
                "type": "DisplayObjectContainer",
                "visible": true,
                "width": 100
            }
        },
        "facingRight": true,
        "filepath": "./resources/scenes/area1files/imgs/frog2.png",
        "height": 100,
        "id": "./resources/scenes/area1files/imgs/frog2.png2",
        "pivot.x": 0,
        "pivot.y": 0,
        "position.x": 200,
        "position.y": 500,
        "rotation": 0.0,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "type": "DisplayObjectContainer",
        "visible": true,
        "width": 100
    },
    "DEFAULT_ID": {
        "alpha": 255,
        "children": null,
        "facingRight": true,
        "filepath": "",
        "height": 100,
        "id": "DEFAULT_ID",
        "pivot.x": 0,
        "pivot.y": 0,
        "position.x": 0,
        "position.y": 0,
        "rotation": 0.0,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "type": "Scene",
        "visible": true,
        "width": 100
    },
    "Layer 1": {
        "alpha": 255,
        "children": {
            "DEFAULT_ID": {
                "alpha": 255,
                "facingRight": true,
                "filepath": "",
                "height": 32,
                "id": "DEFAULT_ID",
                "pivot.x": 0,
                "pivot.y": 0,
                "position.x": 160,
                "position.y": 0,
                "rotation": 0.0,
                "scaleX": 1.0,
                "scaleY": 1.0,
                "type": "DisplayObject",
                "visible": true,
                "width": 32
            }
        },
        "facingRight": true,
        "filepath": "",
        "height": 100,
        "id": "Layer 1",
        "pivot.x": 0,
        "pivot.y": 0,
        "position.x": 0,
        "position.y": 0,
        "rotation": 0.0,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "type": "DisplayObjectContainer",
        "visible": true,
        "width": 100
    }
}